export const ARTICLES = [
    {
        id: "1",
        title: "The Rise of Super-Intelligence: What's Next for AGI?",
        slug: "rise-of-super-intelligence",
        content: "The landscape of artificial intelligence is shifting faster than ever...",
        section: "AI",
        isPremium: true,
        thumbnail: "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&q=80&w=1000",
        videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        createdAt: new Date().toISOString(),
    },
    {
        id: "2",
        title: "Mediterranean Escapes: The Hidden Gems of the Amalfi Coast",
        slug: "mediterranean-escapes",
        content: "Crystal clear waters and sun-drenched cliffs await those who venture...",
        section: "LIFESTYLE",
        isPremium: false,
        thumbnail: "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&q=80&w=1000",
        createdAt: new Date().toISOString(),
    },
    {
        id: "3",
        title: "Global Summit Reaches Historic Agreement on Climate Action",
        slug: "global-summit-climate",
        content: "Leaders from 190 nations have signed a landmark treaty today...",
        section: "WORLD_NEWS",
        isPremium: false,
        thumbnail: "https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?auto=format&fit=crop&q=80&w=1000",
        createdAt: new Date().toISOString(),
    },
    {
        id: "4",
        title: "Mastering Next.js 15: A Comprehensive Tutorial for Developers",
        slug: "mastering-nextjs-15",
        content: "Tutorial content here with code snippets...",
        section: "AI",
        isPremium: true,
        thumbnail: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?auto=format&fit=crop&q=80&w=1000",
        createdAt: new Date().toISOString(),
    },
    {
        id: "5",
        title: "The Art of Slow Living in a Fast-Paced World",
        slug: "art-of-slow-living",
        content: "In an era of constant connectivity, the concept of slow living is gaining...",
        section: "LIFESTYLE",
        isPremium: true,
        thumbnail: "https://images.unsplash.com/photo-1518173946687-a4c8892bbd9f?auto=format&fit=crop&q=80&w=1000",
        createdAt: new Date().toISOString(),
    },
    {
        id: "6",
        title: "New Space Mission to Mars Announced for 2030",
        slug: "mars-mission-2030",
        content: "NASA and partner agencies have unveiled plans for the next phase of...",
        section: "WORLD_NEWS",
        isPremium: false,
        thumbnail: "https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?auto=format&fit=crop&q=80&w=1000",
        createdAt: new Date().toISOString(),
    },
];
